version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: r3_postgres
    restart: always
    environment:
      POSTGRES_USER: r3user
      POSTGRES_PASSWORD: r3password
      POSTGRES_DB: r3carbon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: